version: '2.3'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./proforma:/middlware
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: proforma-middleware
    command: bash -c "uwsgi --http :8000 --wsgi-file wsgi.py.old"
    volumes:
      - type: bind
        source: ./docker-data
        target: /middleware/backup
    expose:
      - "8000"